Добавил переключение треков
MrBlackD/MusApp pull request #3
Opened 2018-09-25 20:31 UTC by SlikSlaks

Добавил отображение длительности треков

2018-09-26 20:30 UTC, MrBlackD requested changes

2018-09-26 20:30 UTC, MrBlackD commented on src/js/components/PlayerPage/PlayerPage.js
> +                <TrackList onClick={(track)=>this.setState({track})} track={track}/>
Поскольку в данный момент вся работа с треками скрыта внутри компонента TrackList, то пробрасывать трек в родителя больше не нужно.

2018-09-26 20:30 UTC, MrBlackD commented on src/js/components/TrackList/TrackList.js
> +            gotDuration: false
gotDuration нигде не используется

2018-09-26 20:30 UTC, MrBlackD commented on src/js/components/TrackList/TrackList.js
> +Player.propTypes={
Компонент TrackList, а propTypes указаны для Player

2018-09-26 20:30 UTC, MrBlackD commented on src/js/components/TrackList/TrackList.js
> +        const currentTrack = this.trackRow[index];
Названия activeTrack и currentTrack все таки путают. Нужно что то другое

2018-09-26 20:30 UTC, MrBlackD commented on src/js/components/TrackList/TrackList.js
> +        this.trackRow = [];
Название переменной не отражает сути

2018-09-29 17:15 UTC, SlikSlaks commented on src/js/components/TrackList/TrackList.js
> +        this.trackRow = [];
Изменено на trackListRows

2018-09-29 17:15 UTC, SlikSlaks commented on src/js/components/TrackList/TrackList.js
> +            gotDuration: false
Удалено

2018-09-29 17:23 UTC, SlikSlaks commented on src/js/components/TrackList/TrackList.js
> +        const currentTrack = this.trackRow[index];
activeTrack = playingTrack
currentTrack = triggeredTrack

2018-10-08 18:21 UTC, MrBlackD submitted a review, later dismissed

2018-10-08 18:21 UTC, MrBlackD commented on src/js/components/PlayerPage/PlayerPage.js
> +  }
конструктор больше не нужен

2018-10-08 18:23 UTC, MrBlackD approved these changes

2018-10-08 18:23 UTC, merged